// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA62bkfNCGLxHzuUjYVoPvDwv48omaXb0',
    appId: '1:270914271583:web:ef1328e537195a1a6cdeea',
    messagingSenderId: '270914271583',
    projectId: 'distress-app-ff499',
    authDomain: 'distress-app-ff499.firebaseapp.com',
    storageBucket: 'distress-app-ff499.appspot.com',
    measurementId: 'G-X3EVR4H5KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsHqqSX8IxK3geaW9Y3WFN4PnxexTonwM',
    appId: '1:270914271583:android:485646de971cadab6cdeea',
    messagingSenderId: '270914271583',
    projectId: 'distress-app-ff499',
    storageBucket: 'distress-app-ff499.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqIxDaqJ4SRYKoxGKCTFX7sOp6Wh5fSvM',
    appId: '1:270914271583:ios:b5b9f6c1a8365aa76cdeea',
    messagingSenderId: '270914271583',
    projectId: 'distress-app-ff499',
    storageBucket: 'distress-app-ff499.appspot.com',
    iosBundleId: 'com.app.distressApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqIxDaqJ4SRYKoxGKCTFX7sOp6Wh5fSvM',
    appId: '1:270914271583:ios:b5b9f6c1a8365aa76cdeea',
    messagingSenderId: '270914271583',
    projectId: 'distress-app-ff499',
    storageBucket: 'distress-app-ff499.appspot.com',
    iosBundleId: 'com.app.distressApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA62bkfNCGLxHzuUjYVoPvDwv48omaXb0',
    appId: '1:270914271583:web:2a696aab39e112bd6cdeea',
    messagingSenderId: '270914271583',
    projectId: 'distress-app-ff499',
    authDomain: 'distress-app-ff499.firebaseapp.com',
    storageBucket: 'distress-app-ff499.appspot.com',
    measurementId: 'G-VRFG6RCX69',
  );
}
